name: Deploy Docker App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~
            rm -rf app
            git clone https://github.com/jihanurrahman33/nishak-portfolio.git app
            cd app

            docker build -t portfolio .

            docker stop portfolio-container || true
            docker rm portfolio-container || true

            # Added restart policy so your app comes back up if the server restarts
            docker run -d --restart unless-stopped -p 80:80 --name portfolio-container portfolio